version: '2'
services:
    smallgis-app:
        image: smallgis
        external_links:
            - smallgis-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=smallgis
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smallgis-mongodb:
        extends:
            file: mongodb.yml
            service: smallgis-mongodb
