version: '2'
services:
    smallgis-mongodb:
        container_name: smallgis-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        command: mongos --configdb smallgis-mongodb-config
    smallgis-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    smallgis-mongodb-config:
        image: mongo:3.3.5
        container_name: smallgis-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
