version: '2'
services:
    smallgis-mongodb:
        container_name: smallgis-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/smallgis/mongodb/:/data/db/
